import type { LtcCareCombination } from "./types";

/** AA 群：照顧管理服務及政策鼓勵服務（AA01–AA12） */
export const aaCodes: LtcCareCombination[] = [
  {
    code: "AA01",
    category: "AA",
    name: "照顧計畫擬訂與服務連結",
    rules: [
      {
        label: "一、",
        text: "內容：",
        children: [
          { label: "1.", text: "承接照管中心轉介長照給付對象。" },
          { label: "2.", text: "至案家與長照給付對象或其家庭照顧者討論，依其長照服務給付額度、照顧問題清單及照顧需求後擬訂照顧計畫。" },
          { label: "3.", text: "照顧計畫送照管中心核定後連結服務或資源。" },
          { label: "4.", text: "每六個月需進行家訪並重新依個案需求擬訂照顧計畫，如發現個案身體狀況改變需重新評估，則通報照管中心進行複評。六個月重新擬訂照顧計畫及複評時等級改變應重新擬訂照顧計畫，均可申報一次。" },
        ],
      },
      { label: "二、", text: "本組合不得與 AA02 於同月併計。" },
      { label: "三、", text: "本組合與 AA02 同月申報總數需合併計算，同月專任個案管理員可申報組數以一百二十組為準，超過一百二十組者，每組減付本組合給（支）付價格百分之十之金額，至多得超額申報至一百五十組，兼任個案管理員可申報組數上限以專任人員可申報組數折半計。" },
      { label: "四、", text: "兼任個案管理員同月於各社區整合型服務中心之申報組數上限同上。" },
      { label: "五、", text: "本組合不扣長照服務給付額度且免部分負擔。" },
    ],
    payment: { kind: "fixed", nt: 1700 },
    remotePayment: { kind: "fixed", nt: 2040 },
    references: ["AA02"],
  },
  {
    code: "AA02",
    category: "AA",
    name: "照顧管理",
    rules: [
      {
        label: "一、",
        text: "內容：",
        children: [
          { label: "1.", text: "依長照給付對象需求或長照需要變化調整照顧計畫。" },
          { label: "2.", text: "執行服務計畫。" },
          { label: "3.", text: "追蹤長照給付對象與各項服務之連結情形。" },
          { label: "4.", text: "每月定期進行服務品質追蹤。" },
          { label: "5.", text: "接受長照給付對象及其家屬照顧者有關長照服務諮詢、申訴及處理。" },
          { label: "6.", text: "協助長照給付對象或其家屬照顧者其他資源連結。" },
        ],
      },
      { label: "二、", text: "申請費用應檢附服務紀錄、照顧計畫異動報告或申訴紀錄。" },
      { label: "三、", text: "本組合不得與 AA01 於同月併計。" },
      { label: "四、", text: "本組合與 AA01 同月申報總數需合併計算，同月專任個案管理員可申報組以一百二十組為準，超過一百二十組者，每組減付本組合給（支）付價格百分之十之金額，至多得超額申報至一百五十組，兼任個案管理員可申報組數上限以專任人員可申報組數折半計。" },
      { label: "五、", text: "兼任個案管理員同月於各社區整合型服務中心之申報組數上限及超額申報組數同上。" },
      { label: "六、", text: "本組合不扣長照服務給付額度且免部分負擔。" },
    ],
    payment: { kind: "fixed", nt: 400 },
    remotePayment: { kind: "fixed", nt: 480 },
    references: ["AA01"],
  },
  {
    code: "AA03",
    category: "AA",
    name: "照顧服務員配合專業服務",
    rules: [
      { label: "一、", text: "內容：照顧服務員至少一次，於專業服務提供者提供專業服務時同行及學習，且應同時段提供居家照顧服務，並參與或協助執行後續長照給付對象專業服務照顧計畫後申請。" },
      { label: "二、", text: "長照給付對象被核定給付專業服務。" },
      { label: "三、", text: "第一點同時段提供之居家照顧服務，應為以下 BA 碼之一：", children: [
        { label: "1.", text: "BA01~BA05、BA07、BA12、BA17d1、BA17d2、BA17e、BA23。" },
        { label: "2.", text: "BA15：個案應為獨居且復能目標包含自行學習家務整理者。" },
      ]},
      { label: "四、", text: "照顧服務員應執行與該專業服務相關之照顧服務，並完整參與長照給付對象專業服務照顧組合後申請。" },
      { label: "五、", text: "每個專業服務照顧組合（C 碼，不含 CC01）只能申請一次。" },
      { label: "六、", text: "本組合不扣長照服務給付額度且免部分負擔。" },
    ],
    payment: { kind: "fixed", nt: 600 },
    remotePayment: { kind: "fixed", nt: 720 },
    references: ["BA01", "BA02", "BA03", "BA04", "BA05", "BA07", "BA12", "BA15", "BA17d1", "BA17d2", "BA17e", "BA23"],
  },
  {
    code: "AA04",
    category: "AA",
    name: "於臨終日提供服務加計",
    rules: [
      { label: "一、", text: "內容：於長照給付對象臨終日或前一日提供居家服務（BA 碼照顧組合），或後一日提供基本身體清潔（BA01），得加計。" },
      { label: "二、", text: "本組合只限申請一次。" },
      { label: "三、", text: "本組合不扣長照服務給付額度且免部分負擔。" },
    ],
    payment: { kind: "fixed", nt: 1200 },
    remotePayment: { kind: "fixed", nt: 1440 },
    references: ["BA01"],
  },
  {
    code: "AA05",
    category: "AA",
    name: "照顧困難之服務加計",
    rules: [
      {
        label: "一、",
        text: "內容：符合以下情形之一者，得於提供服務時加計費用，同服務單位提供同個案服務，一日限加計一次：",
        children: [
          { label: "1.", text: "長照給付對象曾有抗拒照顧或有攻擊行為。" },
          { label: "2.", text: "長照給付對象罹患之疾病具有傳染性（痲瘋、肺結核、梅毒），增加照顧困難度。" },
          { label: "3.", text: "長照給付對象為領有身心障礙證明之慢性精神病患者、自閉症者、智能障礙者及失智症者，增加照顧困難度。" },
          { label: "4.", text: "經確診之失智症者。" },
          { label: "5.", text: "經長照需要等級評定為第五級以上，且為領有身心障礙證明之頑性（難治型）癲癇症者、植物人及罕見疾病患者，增加照顧困難度。" },
          { label: "6.", text: "長照給付對象為領有身心障礙證明，且證明中 ICD 診斷碼註記（腦性麻痺患者：G80；脊髓損傷者：S14、S24、S34）、領有全民健康保險重大傷病證明、或經醫療機構開立診斷證明書之腦性麻痺患者及脊髓損傷者，增加照顧困難度。" },
        ],
      },
      { label: "二、", text: "本組合以日為加計單位。" },
      { label: "三、", text: "本組合限提供照顧服務（BA16 代購或代領或代送服務除外）及專業服務、喘息服務加計。" },
      { label: "四、", text: "本組合不扣長照服務給付額度且免部分負擔。" },
    ],
    payment: { kind: "fixed", nt: 200 },
    remotePayment: { kind: "fixed", nt: 240 },
    references: ["BA16"],
  },
  {
    code: "AA06",
    category: "AA",
    name: "身體照顧困難加計",
    rules: [
      {
        label: "一、",
        text: "內容：符合以下情形之一者，得於提供服務時加計費用，並每日以一次為限：",
        children: [
          { label: "1.", text: "對有管路（含傷口、燒燙傷），或移位困難且體重超過七十公斤需協助之長照給付對象提供 BA01 或 BA07 照顧組合。" },
          { label: "2.", text: "對 ADL 移位或上下樓梯屬完全依賴提供 BA12 照顧組合，或需二名以上照顧服務員同時提供服務才能完成 BA12 照顧組合。" },
          { label: "3.", text: "對 ADL 移位屬可自行坐起，但離床需協助，且體重大於七十公斤提供 BA12 照顧組合。" },
          { label: "4.", text: "對十二歲以下（含）之長照給付對象提供 BA01、BA02 或 BA07 照顧組合。" },
        ],
      },
      { label: "二、", text: "本組合以日為加計單位。" },
      { label: "三、", text: "本組合不扣長照服務給付額度且免部分負擔。" },
    ],
    payment: { kind: "fixed", nt: 200 },
    remotePayment: { kind: "fixed", nt: 240 },
    references: ["BA01", "BA02", "BA07", "BA12"],
  },
  {
    code: "AA07",
    category: "AA",
    name: "家庭照顧功能微弱之服務加計",
    rules: [
      { label: "一、", text: "內容：對長照需要等級評定第四級以上，且家庭照顧者為年齡超過七十五歲或領有身心障礙者證明或獨居之長照給付對象到宅提供 BA01、BA02、BA03、BA04、BA07、BA08、BA10、BA11、BA12 及 BA14 照顧組合時加計。" },
      { label: "二、", text: "本組合以每月為加計單位，每月申請一次。" },
      { label: "三、", text: "本組合不扣長照服務給付額度且免部分負擔。" },
    ],
    payment: { kind: "fixed", nt: 760 },
    remotePayment: { kind: "fixed", nt: 915 },
    references: ["BA01", "BA02", "BA03", "BA04", "BA07", "BA08", "BA10", "BA11", "BA12", "BA14"],
  },
  {
    code: "AA08",
    category: "AA",
    name: "晚間服務",
    rules: [
      { label: "一、", text: "於晚間提供照顧及專業服務（晚上八點至晚上十二點）時加計。" },
      { label: "二、", text: "同服務單位提供同個案服務，一日限加計一次。" },
      { label: "三、", text: "同日 AA08 及 AA09 不得同時申請。" },
      { label: "四、", text: "本組合不扣長照服務給付額度且免部分負擔。" },
    ],
    payment: { kind: "fixed", nt: 385 },
    remotePayment: { kind: "fixed", nt: 465 },
    references: ["AA09"],
  },
  {
    code: "AA09",
    category: "AA",
    name: "例假日服務",
    rules: [
      { label: "一、", text: "於週六、週日或國定假日提供照顧及專業服務、喘息服務時加計。" },
      { label: "二、", text: "同服務單位提供同個案服務，一日限加計一次。" },
      { label: "三、", text: "同日 AA08 及 AA09 不得同時申請。" },
      { label: "四、", text: "本組合不扣長照服務給付額度且免部分負擔。" },
    ],
    payment: { kind: "fixed", nt: 770 },
    remotePayment: { kind: "fixed", nt: 925 },
    references: ["AA08"],
  },
  {
    code: "AA10",
    category: "AA",
    name: "夜間緊急服務",
    rules: [
      { label: "一、", text: "於晚上十二點至隔日六點緊急提供非照顧計畫既定之照顧服務加計。" },
      { label: "二、", text: "一日為一給（支）付單位。" },
      { label: "三、", text: "本組合不扣長照服務給付額度且免部分負擔。" },
    ],
    payment: { kind: "fixed", nt: 1000 },
    remotePayment: { kind: "fixed", nt: 1200 },
  },
  {
    code: "AA11",
    category: "AA",
    name: "照顧服務員進階訓練",
    rules: [
      {
        label: "一、",
        text: "內容：照顧服務人員針對以下對象提供 BA01、BA02、BA04、BA05、BA07、BA13、BA18、BA20、BA23、BA24、BB01~BB14 及 BC01~BC14 照顧組合時加計：",
        children: [
          { label: "1.", text: "對領有身心障礙證明之慢性精神病患者、自閉症者、智能障礙者、失智症者、頑性（難治型）癲癇症者、植物人及罕見疾病患者。" },
          { label: "2.", text: "對經確診之失智症者。" },
          { label: "3.", text: "對領有身心障礙證明，且證明中 ICD 診斷碼註記（腦性麻痺患者：G80；脊髓損傷者：S14、S24、S34）、領有全民健康保險重大傷病證明、或經醫療機構開立診斷證明書之腦性麻痺患者及脊髓損傷者。" },
        ],
      },
      { label: "二、", text: "本組合服務失智症者之照顧服務人員應完成失智症訓練課程；服務本組合其他身心障礙者（不含失智症者）之照顧服務人員應取得長期照顧服務機構設立標準附件二社區式長照機構設立標準表所定身心障礙服務相關訓練證明。" },
      { label: "三、", text: "本組合以日為加計單位，每一位領有身心障礙證明之長照給付對象，每日只限申請一次，但於居家式、社區式長照服務機構得分別計算。" },
      { label: "四、", text: "長期照顧服務機構應訂定本項申報費用回饋完訓照顧服務員之獎勵機制。" },
      { label: "五、", text: "本組合不扣長照服務給付額度且免部分負擔。" },
    ],
    payment: { kind: "fixed", nt: 50 },
    remotePayment: { kind: "fixed", nt: 60 },
    references: ["BA01", "BA02", "BA04", "BA05", "BA07", "BA13", "BA18", "BA20", "BA23", "BA24"],
  },
  {
    code: "AA12",
    category: "AA",
    name: "開立醫師意見書",
    rules: [
      {
        label: "一、",
        text: "內容：",
        children: [
          { label: "1.", text: "承接照管中心轉介之長照給付對象，依衛生福利部公告之醫師意見書，於規定期限內以家訪方式評估個案狀況及長照醫事照護需求，提出長照醫事照護意見，並上傳資訊系統。" },
          { label: "2.", text: "針對已收案之長照給付對象，每六個月開立醫師意見書。" },
          { label: "3.", text: "本項組合每年上限為二次。" },
        ],
      },
      { label: "二、", text: "本組合不扣長照服務給付額度且免部分負擔。" },
    ],
    payment: { kind: "fixed", nt: 1500 },
    remotePayment: { kind: "fixed", nt: 1800 },
  },
];
