import type { LtcCareCombination } from "./types";

/** BC 群：家庭托顧（BC01–BC14，全日/半日各 7 型，對應長照需要等級二至八） */
export const bcCodes: LtcCareCombination[] = [
  {
    code: "BC01",
    category: "BC",
    name: "家庭托顧（全日）--第一型",
    rules: [
      { label: "一、", text: "內容：身體照顧、日常生活照顧服務與安全性照顧、備餐服務。" },
      { label: "二、", text: "以一日為一給（支）付單位。" },
      { label: "三、", text: "適用長照需要等級二級。" },
      { label: "四、", text: "使用交通接送者另計。" },
    ],
    payment: { kind: "fixed", nt: 625 },
    remotePayment: { kind: "fixed", nt: 750 },
    applicableTo: ["daycare"],
  },
  {
    code: "BC02",
    category: "BC",
    name: "家庭托顧（半日）--第一型",
    rules: [
      { label: "一、", text: "內容：身體照顧、日常生活照顧服務與安全性照顧、備餐服務。" },
      { label: "二、", text: "以半日為一給（支）付單位，同日不得申請二次。" },
      { label: "三、", text: "適用長照需要等級二級。" },
      { label: "四、", text: "使用交通接送者另計。" },
    ],
    payment: { kind: "fixed", nt: 315 },
    remotePayment: { kind: "fixed", nt: 375 },
    applicableTo: ["daycare"],
  },
  {
    code: "BC03",
    category: "BC",
    name: "家庭托顧（全日）--第二型",
    rules: [
      { label: "一、", text: "內容：身體照顧、日常生活照顧服務與安全性照顧、備餐服務。" },
      { label: "二、", text: "以一日為一給（支）付單位。" },
      { label: "三、", text: "適用長照需要等級三級。" },
      { label: "四、", text: "使用交通接送者另計。" },
    ],
    payment: { kind: "fixed", nt: 760 },
    remotePayment: { kind: "fixed", nt: 915 },
    applicableTo: ["daycare"],
  },
  {
    code: "BC04",
    category: "BC",
    name: "家庭托顧（半日）--第二型",
    rules: [
      { label: "一、", text: "內容：身體照顧、日常生活照顧服務與安全性照顧、備餐服務。" },
      { label: "二、", text: "以半日為一給（支）付單位，同日不得申請二次。" },
      { label: "三、", text: "適用長照需要等級三級。" },
      { label: "四、", text: "使用交通接送者另計。" },
    ],
    payment: { kind: "fixed", nt: 380 },
    remotePayment: { kind: "fixed", nt: 460 },
    applicableTo: ["daycare"],
  },
  {
    code: "BC05",
    category: "BC",
    name: "家庭托顧（全日）--第三型",
    rules: [
      { label: "一、", text: "內容：身體照顧、日常生活照顧服務與安全性照顧、備餐服務。" },
      { label: "二、", text: "以一日為一給（支）付單位。" },
      { label: "三、", text: "適用長照需要等級四級。" },
      { label: "四、", text: "使用交通接送者另計。" },
    ],
    payment: { kind: "fixed", nt: 785 },
    remotePayment: { kind: "fixed", nt: 945 },
    applicableTo: ["daycare"],
  },
  {
    code: "BC06",
    category: "BC",
    name: "家庭托顧（半日）--第三型",
    rules: [
      { label: "一、", text: "內容：身體照顧、日常生活照顧服務與安全性照顧、備餐服務。" },
      { label: "二、", text: "以半日為一給（支）付單位，同日不得申請二次。" },
      { label: "三、", text: "適用長照需要等級四級。" },
      { label: "四、", text: "使用交通接送者另計。" },
    ],
    payment: { kind: "fixed", nt: 395 },
    remotePayment: { kind: "fixed", nt: 475 },
    applicableTo: ["daycare"],
  },
  {
    code: "BC07",
    category: "BC",
    name: "家庭托顧（全日）--第四型",
    rules: [
      { label: "一、", text: "內容：身體照顧、日常生活照顧服務與安全性照顧、備餐服務。" },
      { label: "二、", text: "以一日為一給（支）付單位。" },
      { label: "三、", text: "適用長照需要等級五級。" },
      { label: "四、", text: "使用交通接送者另計。" },
    ],
    payment: { kind: "fixed", nt: 880 },
    remotePayment: { kind: "fixed", nt: 1055 },
    applicableTo: ["daycare"],
  },
  {
    code: "BC08",
    category: "BC",
    name: "家庭托顧（半日）--第四型",
    rules: [
      { label: "一、", text: "內容：身體照顧、日常生活照顧服務與安全性照顧、備餐服務。" },
      { label: "二、", text: "以半日為一給（支）付單位，同日不得申請二次。" },
      { label: "三、", text: "適用長照需要等級五級。" },
      { label: "四、", text: "使用交通接送者另計。" },
    ],
    payment: { kind: "fixed", nt: 440 },
    remotePayment: { kind: "fixed", nt: 530 },
    applicableTo: ["daycare"],
  },
  {
    code: "BC09",
    category: "BC",
    name: "家庭托顧（全日）--第五型",
    rules: [
      { label: "一、", text: "內容：身體照顧、日常生活照顧服務與安全性照顧、備餐服務。" },
      { label: "二、", text: "以一日為一給（支）付單位。" },
      { label: "三、", text: "適用長照需要等級六級。" },
      { label: "四、", text: "使用交通接送者另計。" },
    ],
    payment: { kind: "fixed", nt: 960 },
    remotePayment: { kind: "fixed", nt: 1155 },
    applicableTo: ["daycare"],
  },
  {
    code: "BC10",
    category: "BC",
    name: "家庭托顧（半日）--第五型",
    rules: [
      { label: "一、", text: "內容：身體照顧、日常生活照顧服務與安全性照顧、備餐服務。" },
      { label: "二、", text: "以半日為一給（支）付單位，同日不得申請二次。" },
      { label: "三、", text: "適用長照需要等級六級。" },
      { label: "四、", text: "使用交通接送者另計。" },
    ],
    payment: { kind: "fixed", nt: 480 },
    remotePayment: { kind: "fixed", nt: 580 },
    applicableTo: ["daycare"],
  },
  {
    code: "BC11",
    category: "BC",
    name: "家庭托顧（全日）--第六型",
    rules: [
      { label: "一、", text: "內容：身體照顧、日常生活照顧服務與安全性照顧、備餐服務。" },
      { label: "二、", text: "以一日為一給（支）付單位。" },
      { label: "三、", text: "適用長照需要等級七級。" },
      { label: "四、", text: "使用交通接送者另計。" },
    ],
    payment: { kind: "fixed", nt: 980 },
    remotePayment: { kind: "fixed", nt: 1180 },
    applicableTo: ["daycare"],
  },
  {
    code: "BC12",
    category: "BC",
    name: "家庭托顧（半日）--第六型",
    rules: [
      { label: "一、", text: "內容：身體照顧、日常生活照顧服務與安全性照顧、備餐服務。" },
      { label: "二、", text: "以半日為一給（支）付單位，同日不得申請二次。" },
      { label: "三、", text: "適用長照需要等級七級。" },
      { label: "四、", text: "使用交通接送者另計。" },
    ],
    payment: { kind: "fixed", nt: 490 },
    remotePayment: { kind: "fixed", nt: 590 },
    applicableTo: ["daycare"],
  },
  {
    code: "BC13",
    category: "BC",
    name: "家庭托顧（全日）--第七型",
    rules: [
      { label: "一、", text: "內容：身體照顧、日常生活照顧服務與安全性照顧、備餐服務。" },
      { label: "二、", text: "以一日為一給（支）付單位。" },
      { label: "三、", text: "適用長照需要等級八級。" },
      { label: "四、", text: "使用交通接送者另計。" },
    ],
    payment: { kind: "fixed", nt: 1040 },
    remotePayment: { kind: "fixed", nt: 1250 },
    applicableTo: ["daycare"],
  },
  {
    code: "BC14",
    category: "BC",
    name: "家庭托顧（半日）--第七型",
    rules: [
      { label: "一、", text: "內容：身體照顧、日常生活照顧服務與安全性照顧、備餐服務。" },
      { label: "二、", text: "以半日為一給（支）付單位，同日不得申請二次。" },
      { label: "三、", text: "適用長照需要等級八級。" },
      { label: "四、", text: "使用交通接送者另計。" },
    ],
    payment: { kind: "fixed", nt: 520 },
    remotePayment: { kind: "fixed", nt: 625 },
    applicableTo: ["daycare"],
  },
];
