import type { LtcCareCombination } from "./types";

/** BB 群：日間照顧（BB01–BB14，全日/半日各 7 型，對應長照需要等級二至八） */
export const bbCodes: LtcCareCombination[] = [
  {
    code: "BB01",
    category: "BB",
    name: "日間照顧（全日）--第一型",
    rules: [
      { label: "一、", text: "內容：生活照顧、健康促進、文康休閒活動、家屬指導及諮詢服務、備餐服務。" },
      { label: "二、", text: "以一日為一給（支）付單位。" },
      { label: "三、", text: "適用長照需要等級二級。" },
      { label: "四、", text: "使用交通接送者另計。" },
      { label: "五、", text: "全日服務，服務提供單位應於向地方主管機關申請特約時，敘明其服務之起迄時點，並經地方主管機關同意。" },
    ],
    payment: { kind: "fixed", nt: 675 },
    remotePayment: { kind: "fixed", nt: 810 },
    applicableTo: ["daycare"],
  },
  {
    code: "BB02",
    category: "BB",
    name: "日間照顧（半日）--第一型",
    rules: [
      { label: "一、", text: "內容：生活照顧、健康促進、文康休閒活動、家屬指導及諮詢服務、備餐服務。" },
      { label: "二、", text: "以半日為一給（支）付單位，同日不得申請二次。" },
      { label: "三、", text: "適用長照需要等級二級。" },
      { label: "四、", text: "使用交通接送者另計。" },
      { label: "五、", text: "半日服務，服務提供單位應於向地方主管機關申請特約時，敘明其服務之起迄時點，並經地方主管機關同意。" },
    ],
    payment: { kind: "fixed", nt: 340 },
    remotePayment: { kind: "fixed", nt: 405 },
    applicableTo: ["daycare"],
  },
  {
    code: "BB03",
    category: "BB",
    name: "日間照顧（全日）--第二型",
    rules: [
      { label: "一、", text: "內容：生活照顧、健康促進、文康休閒活動、家屬指導及諮詢服務、備餐服務。" },
      { label: "二、", text: "以一日為一給（支）付單位。" },
      { label: "三、", text: "適用長照需要等級三級。" },
      { label: "四、", text: "使用交通接送者另計。" },
      { label: "五、", text: "全日服務，服務提供單位應於向地方主管機關申請特約時，敘明其服務之起迄時點，並經地方主管機關同意。" },
    ],
    payment: { kind: "fixed", nt: 840 },
    remotePayment: { kind: "fixed", nt: 1005 },
    applicableTo: ["daycare"],
  },
  {
    code: "BB04",
    category: "BB",
    name: "日間照顧（半日）--第二型",
    rules: [
      { label: "一、", text: "內容：生活照顧、健康促進、文康休閒活動、家屬指導及諮詢服務、備餐服務。" },
      { label: "二、", text: "以半日為一給（支）付單位，同日不得申請二次。" },
      { label: "三、", text: "適用長照需要等級三級。" },
      { label: "四、", text: "使用交通接送者另計。" },
      { label: "五、", text: "半日服務，服務提供單位應於向地方主管機關申請特約時，敘明其服務之起迄時點，並經地方主管機關同意。" },
    ],
    payment: { kind: "fixed", nt: 420 },
    remotePayment: { kind: "fixed", nt: 505 },
    applicableTo: ["daycare"],
  },
  {
    code: "BB05",
    category: "BB",
    name: "日間照顧（全日）--第三型",
    rules: [
      { label: "一、", text: "內容：生活照顧、健康促進、文康休閒活動、家屬指導及諮詢服務、備餐服務。" },
      { label: "二、", text: "以一日為一給（支）付單位。" },
      { label: "三、", text: "適用長照需要等級四級。" },
      { label: "四、", text: "使用交通接送者另計。" },
      { label: "五、", text: "全日服務，服務提供單位應於向地方主管機關申請特約時，敘明其服務之起迄時點，並經地方主管機關同意。" },
    ],
    payment: { kind: "fixed", nt: 920 },
    remotePayment: { kind: "fixed", nt: 1105 },
    applicableTo: ["daycare"],
  },
  {
    code: "BB06",
    category: "BB",
    name: "日間照顧（半日）--第三型",
    rules: [
      { label: "一、", text: "內容：生活照顧、健康促進、文康休閒活動、家屬指導及諮詢服務、備餐服務。" },
      { label: "二、", text: "以半日為一給（支）付單位，同日不得申請二次。" },
      { label: "三、", text: "適用長照需要等級四級。" },
      { label: "四、", text: "使用交通接送者另計。" },
      { label: "五、", text: "半日服務，服務提供單位應於向地方主管機關申請特約時，敘明其服務之起迄時點，並經地方主管機關同意。" },
    ],
    payment: { kind: "fixed", nt: 460 },
    remotePayment: { kind: "fixed", nt: 555 },
    applicableTo: ["daycare"],
  },
  {
    code: "BB07",
    category: "BB",
    name: "日間照顧（全日）--第四型",
    rules: [
      { label: "一、", text: "內容：生活照顧、健康促進、文康休閒活動、家屬指導及諮詢服務、備餐服務。" },
      { label: "二、", text: "以一日為一給（支）付單位。" },
      { label: "三、", text: "適用長照需要等級五級。" },
      { label: "四、", text: "使用交通接送者另計。" },
      { label: "五、", text: "全日服務，服務提供單位應於向地方主管機關申請特約時，敘明其服務之起迄時點，並經地方主管機關同意。" },
    ],
    payment: { kind: "fixed", nt: 1045 },
    remotePayment: { kind: "fixed", nt: 1255 },
    applicableTo: ["daycare"],
  },
  {
    code: "BB08",
    category: "BB",
    name: "日間照顧（半日）--第四型",
    rules: [
      { label: "一、", text: "內容：生活照顧、健康促進、文康休閒活動、家屬指導及諮詢服務、備餐服務。" },
      { label: "二、", text: "以半日為一給（支）付單位，同日不得申請二次。" },
      { label: "三、", text: "適用長照需要等級五級。" },
      { label: "四、", text: "使用交通接送者另計。" },
      { label: "五、", text: "半日服務，服務提供單位應於向地方主管機關申請特約時，敘明其服務之起迄時點，並經地方主管機關同意。" },
    ],
    payment: { kind: "fixed", nt: 525 },
    remotePayment: { kind: "fixed", nt: 630 },
    applicableTo: ["daycare"],
  },
  {
    code: "BB09",
    category: "BB",
    name: "日間照顧（全日）--第五型",
    rules: [
      { label: "一、", text: "內容：生活照顧、健康促進、文康休閒活動、家屬指導及諮詢服務、備餐服務。" },
      { label: "二、", text: "以一日為一給（支）付單位。" },
      { label: "三、", text: "適用長照需要等級六級。" },
      { label: "四、", text: "使用交通接送者另計。" },
      { label: "五、", text: "全日服務，服務提供單位應於向地方主管機關申請特約時，敘明其服務之起迄時點，並經地方主管機關同意。" },
    ],
    payment: { kind: "fixed", nt: 1130 },
    remotePayment: { kind: "fixed", nt: 1355 },
    applicableTo: ["daycare"],
  },
  {
    code: "BB10",
    category: "BB",
    name: "日間照顧（半日）--第五型",
    rules: [
      { label: "一、", text: "內容：生活照顧、健康促進、文康休閒活動、家屬指導及諮詢服務、備餐服務。" },
      { label: "二、", text: "以半日為一給（支）付單位，同日不得申請二次。" },
      { label: "三、", text: "適用長照需要等級六級。" },
      { label: "四、", text: "使用交通接送者另計。" },
      { label: "五、", text: "半日服務，服務提供單位應於向地方主管機關申請特約時，敘明其服務之起迄時點，並經地方主管機關同意。" },
    ],
    payment: { kind: "fixed", nt: 565 },
    remotePayment: { kind: "fixed", nt: 680 },
    applicableTo: ["daycare"],
  },
  {
    code: "BB11",
    category: "BB",
    name: "日間照顧（全日）--第六型",
    rules: [
      { label: "一、", text: "內容：生活照顧、健康促進、文康休閒活動、家屬指導及諮詢服務、備餐服務。" },
      { label: "二、", text: "以一日為一給（支）付單位。" },
      { label: "三、", text: "適用長照需要等級七級。" },
      { label: "四、", text: "使用交通接送者另計。" },
      { label: "五、", text: "全日服務，服務提供單位應於向地方主管機關申請特約時，敘明其服務之起迄時點，並經地方主管機關同意。" },
    ],
    payment: { kind: "fixed", nt: 1210 },
    remotePayment: { kind: "fixed", nt: 1450 },
    applicableTo: ["daycare"],
  },
  {
    code: "BB12",
    category: "BB",
    name: "日間照顧（半日）--第六型",
    rules: [
      { label: "一、", text: "內容：生活照顧、健康促進、文康休閒活動、家屬指導及諮詢服務、備餐服務。" },
      { label: "二、", text: "以半日為一給（支）付單位，同日不得申請二次。" },
      { label: "三、", text: "適用長照需要等級七級。" },
      { label: "四、", text: "使用交通接送者另計。" },
      { label: "五、", text: "半日服務，服務提供單位應於向地方主管機關申請特約時，敘明其服務之起迄時點，並經地方主管機關同意。" },
    ],
    payment: { kind: "fixed", nt: 605 },
    remotePayment: { kind: "fixed", nt: 725 },
    applicableTo: ["daycare"],
  },
  {
    code: "BB13",
    category: "BB",
    name: "日間照顧（全日）--第七型",
    rules: [
      { label: "一、", text: "內容：生活照顧、健康促進、文康休閒活動、家屬指導及諮詢服務、備餐服務。" },
      { label: "二、", text: "以一日為一給（支）付單位。" },
      { label: "三、", text: "適用長照需要等級八級。" },
      { label: "四、", text: "使用交通接送者另計。" },
      { label: "五、", text: "全日服務，服務提供單位應於向地方主管機關申請特約時，敘明其服務之起迄時點，並經地方主管機關同意。" },
    ],
    payment: { kind: "fixed", nt: 1285 },
    remotePayment: { kind: "fixed", nt: 1540 },
    applicableTo: ["daycare"],
  },
  {
    code: "BB14",
    category: "BB",
    name: "日間照顧（半日）--第七型",
    rules: [
      { label: "一、", text: "內容：生活照顧、健康促進、文康休閒活動、家屬指導及諮詢服務、備餐服務。" },
      { label: "二、", text: "以半日為一給（支）付單位，同日不得申請二次。" },
      { label: "三、", text: "適用長照需要等級八級。" },
      { label: "四、", text: "使用交通接送者另計。" },
      { label: "五、", text: "半日服務，服務提供單位應於向地方主管機關申請特約時，敘明其服務之起迄時點，並經地方主管機關同意。" },
    ],
    payment: { kind: "fixed", nt: 645 },
    remotePayment: { kind: "fixed", nt: 770 },
    applicableTo: ["daycare"],
  },
];
