import type { LucideIcon } from "lucide-react";
import {
  ShieldCheckIcon,
  HeartPulseIcon,
  SettingsIcon,
  StarIcon,
  HomeIcon,
  SunIcon,
  BuildingIcon,
  HospitalIcon,
  ShieldIcon,
  StethoscopeIcon,
  BabyIcon,
  AccessibilityIcon,
  UsersIcon,
  UserCheckIcon,
  FileTextIcon,
  HeartHandshakeIcon,
  AlertTriangleIcon,
  ActivityIcon,
  SparklesIcon,
  PillIcon,
  SyringeIcon,
  BugIcon,
  FlaskConicalIcon,
  BrainCircuitIcon,
  BriefcaseMedicalIcon,
  ClipboardCheckIcon,
} from "lucide-react";

export interface SchoolNavItem {
  href: string;
  label: string;
  title: string;
  icon?: LucideIcon;
  desc?: string;
  comingSoon?: boolean;
}

export interface SchoolNavSection {
  group: string;
  items: SchoolNavItem[];
}

export const schoolNavSections: SchoolNavSection[] = [
  {
    group: "居家服務機構",
    items: [
      {
        href: "/school/home-care",
        label: "評鑑基準總覽",
        title: "居家服務機構評鑑基準總覽",
        icon: HomeIcon,
        desc: "32 項評鑑基準完整說明",
      },
      {
        href: "/school/home-care/client-rights",
        label: "壹、個案權益保障",
        title: "個案權益保障評鑑基準（項目 1–4）",
        icon: ShieldCheckIcon,
        desc: "服務資訊公開、個案權益、隱私保護、申訴機制",
      },
      {
        href: "/school/home-care/professional-quality",
        label: "貳、專業照護品質",
        title: "專業照護品質評鑑基準（項目 5–14）",
        icon: HeartPulseIcon,
        desc: "入案評估、服務計畫、緊急處理、督導訪視",
      },
      {
        href: "/school/home-care/management",
        label: "參、經營管理效能",
        title: "經營管理效能評鑑基準（項目 15–30）",
        icon: SettingsIcon,
        desc: "行政管理、人員配置、財務、品質改善",
      },
      {
        href: "/school/home-care/bonus",
        label: "加分題",
        title: "居家服務機構評鑑加分題（項目 31–32）",
        icon: StarIcon,
        desc: "創新服務、照顧者支持",
      },
    ],
  },
  {
    group: "日間照顧機構",
    items: [
      {
        href: "/school/daycare",
        label: "評鑑基準總覽",
        title: "日間照顧機構評鑑基準總覽",
        icon: SunIcon,
        desc: "115 年度 43 項評鑑基準完整說明，另含 2 項加分題",
      },
      {
        href: "/school/daycare/client-rights",
        label: "壹、個案權益保障",
        title: "個案權益保障評鑑基準（項目 1–4）",
        icon: ShieldCheckIcon,
        desc: "服務資訊公開、意見反應申訴機制、服務契約簽訂、個人資料管理",
      },
      {
        href: "/school/daycare/professional-quality",
        label: "貳、專業照護品質",
        title: "專業照護品質評鑑基準（項目 5–22）",
        icon: HeartPulseIcon,
        desc: "服務對象評估、照顧計畫、追蹤評值、活動辦理、協助服藥、健康管理、防疫機制",
      },
      {
        href: "/school/daycare/management",
        label: "參、經營管理效能",
        title: "經營管理效能評鑑基準（項目 23–37）",
        icon: SettingsIcon,
        desc: "業務計畫、人力設置、訓練、留任率、財務管理、緊急事件、性騷擾防治",
      },
      {
        href: "/school/daycare/safety-environment",
        label: "肆、安全環境設備",
        title: "安全環境設備評鑑基準（項目 38–43）",
        icon: ShieldIcon,
        desc: "高齡友善環境、盥洗衛生設備、休息場所、飲用水、廚房衛生、病媒防治",
      },
    ],
  },
  {
    group: "住宿型照顧機構",
    items: [
      {
        href: "/school/nursing-home",
        label: "評鑑基準總覽",
        title: "住宿型照顧機構評鑑基準總覽",
        icon: BuildingIcon,
        desc: "75 項評鑑基準完整說明",
      },
      {
        href: "/school/nursing-home/management",
        label: "A、經營管理效能",
        title: "經營管理效能評鑑基準（項目 1–15）",
        icon: SettingsIcon,
        desc: "人員配置、工作手冊、訓練計畫、勞動條件",
      },
      {
        href: "/school/nursing-home/professional-quality",
        label: "B、專業照護品質",
        title: "專業照護品質評鑑基準（項目 16–47）",
        icon: HeartPulseIcon,
        desc: "照護計畫、醫療服務、感染管制、膳食、復健",
      },
      {
        href: "/school/nursing-home/safety-environment",
        label: "C、安全環境設備",
        title: "安全環境設備評鑑基準（項目 48–63）",
        icon: ShieldIcon,
        desc: "空間設備、消防安全、無障礙設施、緊急應變",
      },
      {
        href: "/school/nursing-home/client-rights",
        label: "D、個案權益保障",
        title: "個案權益保障評鑑基準（項目 64–72）",
        icon: ShieldCheckIcon,
        desc: "個案資料、服務契約、申訴機制、臨終照護",
      },
      {
        href: "/school/nursing-home/innovation",
        label: "E、服務改進創新",
        title: "服務改進創新評鑑基準（項目 73–75）",
        icon: StarIcon,
        desc: "前次評鑑改善、創新服務、違規事件",
      },
    ],
  },
  {
    group: "居家護理所",
    items: [
      {
        href: "/school/home-nursing",
        label: "評鑑基準總覽",
        title: "居家護理所評鑑基準總覽",
        icon: StethoscopeIcon,
        desc: "8 項評鑑基準完整說明",
      },
      {
        href: "/school/home-nursing/management",
        label: "A、經營管理",
        title: "經營管理評鑑基準（項目 1–5）",
        icon: SettingsIcon,
        desc: "社區資源、感染管制、人員安全、緊急事件、品質監測",
      },
      {
        href: "/school/home-nursing/care-management",
        label: "B、照護管理",
        title: "照護管理評鑑基準（項目 6–8）",
        icon: HeartPulseIcon,
        desc: "機構資訊管理、個案照護管理、加分項目",
      },
    ],
  },
  {
    group: "產後護理之家",
    items: [
      {
        href: "/school/postpartum-care",
        label: "評鑑基準總覽",
        title: "產後護理之家評鑑基準總覽",
        icon: BabyIcon,
        desc: "17 項評鑑基準完整說明",
      },
      {
        href: "/school/postpartum-care/administration",
        label: "A、行政組織、經營管理與服務對象權益保障",
        title: "行政組織、經營管理與服務對象權益保障（項目 1–5）",
        icon: SettingsIcon,
        desc: "人員配置、教育訓練、感染管制、意外事件、品質管理",
      },
      {
        href: "/school/postpartum-care/professional-care",
        label: "B、專業服務與生活照顧",
        title: "專業服務與生活照顧（項目 6–13）",
        icon: HeartPulseIcon,
        desc: "產婦照護、嬰兒照護、親子關係、衛教課程、出住院評估、緊急狀況、哺乳、母乳貯存",
      },
      {
        href: "/school/postpartum-care/safety-environment",
        label: "C、環境設施與安全維護",
        title: "環境設施與安全維護（項目 14–15）",
        icon: ShieldIcon,
        desc: "疏散避難系統、嬰兒疏散SOP、天災緊急應變",
      },
      {
        href: "/school/postpartum-care/special-items",
        label: "D、特別事項",
        title: "特別事項（項目 16–17）",
        icon: StarIcon,
        desc: "配合政策加分、重大異常情事試評扣分項",
      },
    ],
  },
  {
    group: "一般護理之家",
    items: [
      {
        href: "/school/general-nursing-home",
        label: "評鑑基準總覽",
        title: "一般護理之家評鑑基準總覽",
        icon: HospitalIcon,
        desc: "15 項評鑑基準完整說明",
      },
      {
        href: "/school/general-nursing-home/administration",
        label: "A、行政組織、經營管理與服務對象權益保障",
        title: "行政組織、經營管理與服務對象權益保障（項目 1–5）",
        icon: SettingsIcon,
        desc: "負責人管理、人員配置、緊急事件、防疫機制、安寧療護",
      },
      {
        href: "/school/general-nursing-home/professional-care",
        label: "B、專業服務與生活照顧",
        title: "專業服務與生活照顧（項目 6–8）",
        icon: HeartPulseIcon,
        desc: "照護需求評估、整合性照顧、品質監測指標",
      },
      {
        href: "/school/general-nursing-home/safety-environment",
        label: "C、環境設施與安全維護",
        title: "環境設施與安全維護（項目 9–12）",
        icon: ShieldIcon,
        desc: "災害應變計畫、疏散避難、個別化疏散策略、情境演練",
      },
      {
        href: "/school/general-nursing-home/special-items",
        label: "D、特別事項",
        title: "特別事項（項目 13–15）",
        icon: StarIcon,
        desc: "創新政策執行、口腔健康照護、試評扣分項",
      },
    ],
  },
  {
    group: "醫院評鑑",
    items: [
      {
        href: "/school/hospital",
        label: "評鑑基準總覽",
        title: "醫院評鑑基準總覽",
        icon: HospitalIcon,
        desc: "124 條評鑑基準完整說明",
      },
      {
        href: "/school/hospital/strategy",
        label: "1.1 醫院經營策略",
        title: "醫院經營策略（項目 1–5）",
        icon: SettingsIcon,
        desc: "院務發展計畫、組織架構、品質管理、績效評估",
      },
      {
        href: "/school/hospital/staff-support",
        label: "1.2 員工管理與支持制度",
        title: "員工管理與支持制度（項目 6–12）",
        icon: UsersIcon,
        desc: "員工支持、申訴機制、職業安全、勞動條件",
      },
      {
        href: "/school/hospital/human-resources",
        label: "1.3 人力資源管理",
        title: "人力資源管理（項目 13–22）",
        icon: UserCheckIcon,
        desc: "醫師、護理、醫事人員配置、訓練、繼續教育",
      },
      {
        href: "/school/hospital/medical-records",
        label: "1.4 病歷、資訊與溝通管理",
        title: "病歷、資訊與溝通管理（項目 23–26）",
        icon: FileTextIcon,
        desc: "病歷書寫、資訊安全、醫療資訊系統、溝通",
      },
      {
        href: "/school/hospital/safety-environment",
        label: "1.5 安全的環境與設備",
        title: "安全的環境與設備（項目 27–33）",
        icon: ShieldIcon,
        desc: "建築安全、消防、醫療設備、危險物品、廢棄物",
      },
      {
        href: "/school/hospital/patient-services",
        label: "1.6 病人導向之服務與管理",
        title: "病人導向之服務與管理（項目 34–37）",
        icon: HeartHandshakeIcon,
        desc: "服務資訊、就醫流程、滿意度、社區健康促進",
      },
      {
        href: "/school/hospital/risk-management",
        label: "1.7 風險與危機管理",
        title: "風險與危機管理（項目 38–42）",
        icon: AlertTriangleIcon,
        desc: "風險管理、醫療事故、緊急應變、大量傷患、危機溝通",
      },
      {
        href: "/school/hospital/patient-rights",
        label: "2.1 病人及家屬權責",
        title: "病人及家屬權責（項目 43–46）",
        icon: ShieldCheckIcon,
        desc: "病人權利、知情同意、隱私保護、申訴機制",
      },
      {
        href: "/school/hospital/care-quality",
        label: "2.2 醫療照護品質與安全管理",
        title: "醫療照護品質與安全管理（項目 47–49）",
        icon: ActivityIcon,
        desc: "品質指標、病人安全文化、異常事件通報",
      },
      {
        href: "/school/hospital/care-execution",
        label: "2.3 醫療照護之執行與評估",
        title: "醫療照護之執行與評估（項目 50–65）",
        icon: StethoscopeIcon,
        desc: "入院評估、照護計畫、疼痛管理、跌倒壓傷、出院計畫",
      },
      {
        href: "/school/hospital/special-care",
        label: "2.4 特殊照護服務",
        title: "特殊照護服務（項目 66–89）",
        icon: SparklesIcon,
        desc: "透析、化療、輸血、內視鏡、精神科、婦產科等",
      },
      {
        href: "/school/hospital/medication-safety",
        label: "2.5 用藥安全",
        title: "用藥安全（項目 90–98）",
        icon: PillIcon,
        desc: "藥品管理、處方開立、調劑、給藥安全、高警訊藥品",
      },
      {
        href: "/school/hospital/anesthesia-surgery",
        label: "2.6 麻醉與手術",
        title: "麻醉與手術（項目 99–107）",
        icon: SyringeIcon,
        desc: "手術安全查核、麻醉前評估、手術室安全、術後照護",
      },
      {
        href: "/school/hospital/infection-control",
        label: "2.7 感染管制",
        title: "感染管制（項目 108–110）",
        icon: BugIcon,
        desc: "感染管制組織、標準防護措施、醫療照護相關感染監測",
      },
      {
        href: "/school/hospital/lab-pathology",
        label: "2.8 檢驗、病理與放射作業",
        title: "檢驗、病理與放射作業（項目 111–124）",
        icon: FlaskConicalIcon,
        desc: "檢驗品質、血庫、病理、放射、MRI、CT、超音波",
      },
    ],
  },
  {
    group: "兒少安置機構",
    items: [
      {
        href: "/school/youth-care",
        label: "評鑑基準總覽",
        title: "兒少安置機構評鑑基準總覽",
        icon: UsersIcon,
        desc: "112年度 35 項評鑑基準完整說明",
      },
      {
        href: "/school/youth-care/administration",
        label: "壹、行政組織與經營管理",
        title: "行政組織與經營管理評鑑基準（項目 1–6）",
        icon: SettingsIcon,
        desc: "董事會功能、行政組織運作、員工手冊、人員資格、訓練進修、勞動條件",
      },
      {
        href: "/school/youth-care/environment",
        label: "貳、建築物環境及設施設備",
        title: "建築物環境及設施設備評鑑基準（項目 7–14）",
        icon: BuildingIcon,
        desc: "整體環境衛生、機構配置、醫療保健、食物冷凍設備、公共安全、危機事故、飲食衛生、健康醫療",
      },
      {
        href: "/school/youth-care/professional",
        label: "參、專業服務",
        title: "專業服務評鑑基準（項目 15–28）",
        icon: HeartPulseIcon,
        desc: "個案紀錄、輔導目標、服務品質（2歲以下/以上雙版本）、權益保障、資源結合、專業訓練",
      },
      {
        href: "/school/youth-care/finance",
        label: "肆、財務管理",
        title: "財務管理評鑑基準（項目 29）",
        icon: FileTextIcon,
        desc: "依財務查核結果計分，共4次查核，20分",
      },
      {
        href: "/school/youth-care/innovation",
        label: "伍、特殊事項或措施",
        title: "特殊事項或措施（含創新服務方案）評鑑基準（項目 30–35）",
        icon: StarIcon,
        desc: "違規扣分、收容多元加分、服務學習、社工薪資、COVID防疫、創新服務",
      },
    ],
  },
  {
    group: "老人福利機構",
    items: [
      {
        href: "/school/elderly-welfare",
        label: "評鑑基準總覽",
        title: "老人福利機構評鑑基準總覽",
        icon: HeartHandshakeIcon,
        desc: "77 項評鑑基準完整說明",
      },
      {
        href: "/school/elderly-welfare/management",
        label: "A、經營管理效能",
        title: "經營管理效能評鑑基準（項目 1–15）",
        icon: SettingsIcon,
        desc: "工作手冊、人員配置、訓練、感染管制、危機管理",
      },
      {
        href: "/school/elderly-welfare/professional-quality",
        label: "B、專業照護品質",
        title: "專業照護品質評鑑基準（項目 16–46）",
        icon: HeartPulseIcon,
        desc: "社工服務、護理照護、用藥管理、復能活動、品質監測",
      },
      {
        href: "/school/elderly-welfare/safety-environment",
        label: "C、安全環境設備",
        title: "安全環境設備評鑑基準（項目 47–62）",
        icon: ShieldIcon,
        desc: "建築安全、消防設備、無障礙設施、緊急應變",
      },
      {
        href: "/school/elderly-welfare/client-rights",
        label: "D、個案權益保障",
        title: "個案權益保障評鑑基準（項目 63–71）",
        icon: ShieldCheckIcon,
        desc: "服務資訊、服務契約、個資保護、申訴機制、滿意度調查",
      },
      {
        href: "/school/elderly-welfare/innovation",
        label: "E、服務改進創新",
        title: "服務改進創新評鑑基準（項目 72–74）",
        icon: StarIcon,
        desc: "前次評鑑缺失改善、創新服務、違規事件改善",
      },
      {
        href: "/school/elderly-welfare/bonus",
        label: "F、加分題",
        title: "加分題評鑑基準（項目 75–77）",
        icon: SparklesIcon,
        desc: "人才培育、智慧照護、在地安老服務",
      },
    ],
  },
  {
    group: "身心障礙福利機構",
    items: [
      {
        href: "/school/disability-welfare",
        label: "評鑑指標總覽",
        title: "身心障礙福利機構評鑑指標總覽（109年度）",
        icon: AccessibilityIcon,
        desc: "49 項評鑑指標完整說明",
      },
      {
        href: "/school/disability-welfare/administration",
        label: "一、行政組織及經營管理",
        title: "行政組織及經營管理（項目 1–11）",
        icon: SettingsIcon,
        desc: "董事會運作、機構管理、員工管理、專業人力、會計財務",
      },
      {
        href: "/school/disability-welfare/environment",
        label: "二、環境設施及安全維護",
        title: "環境設施及安全維護（項目 12–31）",
        icon: ShieldCheckIcon,
        desc: "浴廁設施、無障礙、消防安全、緊急應變、環境衛生",
      },
      {
        href: "/school/disability-welfare/professional",
        label: "三、專業服務",
        title: "專業服務（項目 32–49）",
        icon: HeartPulseIcon,
        desc: "ISP、專業團隊、輔具、健康管理、膳食、社區與家庭",
      },
    ],
  },
  {
    group: "托嬰中心",
    items: [
      {
        href: "/school/infant-daycare",
        label: "評鑑基準總覽",
        title: "托嬰中心評鑑基準總覽",
        icon: BabyIcon,
        desc: "60 項評鑑基準完整說明",
      },
      {
        href: "/school/infant-daycare/administration",
        label: "一、行政管理",
        title: "行政管理評鑑基準（項目 1–11）",
        icon: SettingsIcon,
        desc: "立案行政、員工訓練、人事管理、文書檔案、財務安全、兒童權益保障",
      },
      {
        href: "/school/infant-daycare/childcare-activities",
        label: "二、托育活動",
        title: "托育活動評鑑基準（項目 12–36）",
        icon: HeartPulseIcon,
        desc: "關係建立與互動、環境規劃、活動設計、寶寶日誌、親師交流",
      },
      {
        href: "/school/infant-daycare/health-safety",
        label: "三、健康安全",
        title: "健康安全評鑑基準（項目 37–60）",
        icon: ShieldCheckIcon,
        desc: "健康管理、飲食衛生、給藥委託、衛生設備、環境安全、感染管制",
      },
    ],
  },
  {
    group: "精神護理之家",
    items: [
      {
        href: "/school/psychiatric-nursing-home",
        label: "評鑑總覽",
        title: "精神護理之家評鑑總覽",
        icon: BrainCircuitIcon,
        desc: "115年度精神護理之家評鑑基準，共5大面向36條指標",
      },
      {
        href: "/school/psychiatric-nursing-home/management",
        label: "A 經營管理效能",
        title: "A、經營管理效能（A1.1–A5.1）",
        icon: SettingsIcon,
        desc: "業務計畫、人員配置、工作人員權益、教育訓練、資料管理，共9條",
      },
      {
        href: "/school/psychiatric-nursing-home/professional-care",
        label: "B 專業照護品質",
        title: "B、專業照護品質（B1.1–B3.2）",
        icon: HeartPulseIcon,
        desc: "住民服務計畫、防疫機制、跨專業照護、品質監測、膳食服務，共21條",
      },
      {
        href: "/school/psychiatric-nursing-home/safety-facilities",
        label: "C 安全維護及設施設備",
        title: "C、安全維護及設施設備（C1.1–C1.3）",
        icon: ShieldIcon,
        desc: "疏散避難系統、火災應變計畫、夜間演練，共3條（含1項重點項目）",
      },
      {
        href: "/school/psychiatric-nursing-home/resident-rights",
        label: "D 住民權益保障",
        title: "D、住民權益保障（D1.1–D1.2）",
        icon: UsersIcon,
        desc: "尊重住民信仰、推動安寧緩和療護及病人自主權利，共2條",
      },
      {
        href: "/school/psychiatric-nursing-home/innovation",
        label: "E 創新及改革",
        title: "E、創新及改革（E1.1）",
        icon: SparklesIcon,
        desc: "創新或特色措施具有成效並公開分享，共1條",
      },
    ],
  },
  {
    group: "精神復健機構",
    items: [
      {
        href: "/school/psychiatric-rehabilitation-institution",
        label: "評鑑總覽",
        title: "精神復健機構評鑑總覽",
        icon: BriefcaseMedicalIcon,
        desc: "115年度精神復健機構評鑑基準，含日間型36條與住宿型40條",
      },
      {
        href: "/school/psychiatric-rehabilitation-institution/management",
        label: "第1章 經營管理",
        title: "第1章、經營管理（1.1–1.10/1.12）",
        icon: SettingsIcon,
        desc: "負責人經營管理、人力穩定性、督導訓練、環境設施，日間型10條/住宿型12條",
      },
      {
        href: "/school/psychiatric-rehabilitation-institution/rehabilitation",
        label: "第2章 復健服務",
        title: "第2章、復健服務（2.1–2.14）",
        icon: HeartHandshakeIcon,
        desc: "復健評估、社區生活訓練、就業輔導、社區融合，日間型14條/住宿型14條",
      },
      {
        href: "/school/psychiatric-rehabilitation-institution/service-quality",
        label: "第3章 服務品質",
        title: "第3章、服務品質（3.1–3.12/3.14）",
        icon: ClipboardCheckIcon,
        desc: "工作手冊、收結案標準、權益維護、緊急應變，日間型12條/住宿型14條",
      },
    ],
  },
];
